# Python for AI Development
## AIAT 111 - Unit 1: Introduction to AI and Applications

---

## 📚 Learning Objectives

By completing this notebook, you will:
- Review Python basics essential for AI development
- Work with lists, dictionaries, loops, and conditionals
- Use NumPy for matrix operations
- Read and write files in Python
- Prepare Python code for AI applications

---

## 🔗 Where this fits

**Builds on:** Unit 1, lesson 01 "AI Introduction" — the vocabulary; this lesson sets up the NumPy/file-handling tooling every later notebook uses.

**Used later in:** Course 05 (AIAT 115) — Unit 1, where the same NumPy array thinking is scaled to full DataFrames.

---


## 🎯 Why an array library earns a whole lesson

`import numpy as np` looks like housekeeping. It is not. When the NumPy team
finally described their library in *Nature* in 2020, they justified it with two
specific results: NumPy "was an important part of the software stack used in the
discovery of gravitational waves and the first imaging of a black hole" (Harris
et al., 2020 — reference 1 at the foot of this notebook). The LIGO detection
announced in 2016 and the Event Horizon Telescope image released in 2019 were,
at the level of code, enormous numbers of operations on arrays of numbers.

Nothing in this notebook is conceptually harder than what those pipelines do.
They are the same four moves: put numbers in an array, give the array a shape,
apply an operation to the whole array at once, and read results back from a file.

### What goes wrong without arrays

A Python list stores a pointer to a separate Python object per element, and a
`for` loop pays a fresh interpreter step per item. A NumPy array stores one
contiguous block of raw numbers and hands the loop to compiled C. On the
five-element toy below the difference is invisible — which is exactly the trap.
On the arrays a real model touches (one 224×224 colour image is already 150,528
numbers, and a training batch is 32 of those) the list version is not "slower",
it is unusable. Every later notebook in this diploma assumes you reached for the array.


## 1. Python Basics Review

Essential Python concepts for AI development:


## 📥 Inputs & 📤 Outputs

**Inputs:** What we use in this notebook

- Libraries and concepts as introduced in this notebook; see prerequisites and code comments.

**Outputs:** What you'll see when you run the cells

- Printed results, figures, and summaries as shown when you run the cells.

---

In [1]:
# Lists - Essential for data manipulation
data_points = [1, 2, 3, 4, 5]
print(f"Data points: {data_points}")
print(f"Sum: {sum(data_points)}")
print(f"Average: {sum(data_points) / len(data_points)}")


Data points: [1, 2, 3, 4, 5]
Sum: 15
Average: 3.0


In [2]:
# Dictionaries hold labeled facts about one entity — the shape most datasets take
# before they become tables, so being fluent with them pays off in every ML notebook.
# Dictionaries - For structured data
student_data = {
    'name': 'Ahmed',
    'age': 22,
    'courses': ['AI', 'ML', 'NLP'],
    'grades': {'AI': 95, 'ML': 88, 'NLP': 92}
}

# Read single fields out, then aggregate across the nested grades dict — a mini data-analysis step.
print(f"Student: {student_data['name']}")
print(f"Average grade: {sum(student_data['grades'].values()) / len(student_data['grades'])}")

Student: Ahmed
Average grade: 91.66666666666667


In [3]:
# Loops and comprehensions are how we process whole datasets one record at a time;
# here we compute an average manually before NumPy does it for us later.
# Loops - For processing data
scores = [85, 90, 78, 92, 88]
total = 0
for score in scores:
    total += score
    
average = total / len(scores)
print(f"Average score: {average}")

# List comprehension (Pythonic way)
squared = [x**2 for x in range(1, 6)]
print(f"Squared numbers: {squared}")

Average score: 86.6
Squared numbers: [1, 4, 9, 16, 25]


## 2. NumPy for Matrix Operations

NumPy is essential for AI as it provides efficient numerical operations:


In [4]:
# NumPy arrays are the core data structure of AI: every image, dataset, and model
# weight you will meet later is stored as an n-dimensional array like these.
import numpy as np

# Creating arrays
vector = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Shape tells you the dimensions — the first thing to check when debugging any ML code.
print(f"Vector: {vector}")
print(f"Matrix shape: {matrix.shape}")
print(f"\nMatrix:\n{matrix}")

Vector: [1 2 3 4 5]
Matrix shape: (3, 3)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Matrix operations - Essential for AI

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)
print(f"Matrix A:\n{A}")
print(f"\nMatrix B:\n{B}")
print(f"\nA × B:\n{result}")


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A × B:
[[19 22]
 [43 50]]


In [6]:
# File I/O in Python - Reading and writing files

# Writing to a file
data = "AI, Machine Learning, Deep Learning, NLP"

with open('ai_topics.txt', 'w') as f:
    f.write(data)

print("✅ Data written to file")


✅ Data written to file


In [7]:
# Reading from a file
with open('ai_topics.txt', 'r') as f:
    content = f.read()

print(f"File content: {content}")
topics = content.split(', ')
print(f"\nTopics: {topics}")


File content: AI, Machine Learning, Deep Learning, NLP

Topics: ['AI', 'Machine Learning', 'Deep Learning', 'NLP']


## 💬 Discuss

You now have three containers: a **list**, a **dictionary**, and a **NumPy
array**. The choice is not cosmetic — it decides what you can compute and what
you can silently get wrong. Argue these:

1. The student record above was a dictionary (`name`, `age`, `grades`); the
   matrix was an array. **What breaks first** if you force each one into the
   other's shape? Name a concrete field that has no sensible home in an array.
2. We wrote `AI, Machine Learning, Deep Learning, NLP` to a file and parsed it by
   splitting on commas. Name a realistic value that would corrupt that file
   *without raising an error*, then decide: do you fix the parser, change the
   format, or refuse the data? Defend the choice to whoever sent you the file.
3. NumPy insists every element of an array has the same type — which rules out a
   table with a name column and an age column. Is that restriction a defect or a
   feature? Use the matrix multiplication above to support your answer.


## Summary

In this notebook, we reviewed:
- Python basics: lists, dictionaries, loops, conditionals
- NumPy for matrix operations
- File I/O operations
- Practical data processing for AI

**Next Steps:**
- Complete exercises in `exercises/` folder
- Practice with NumPy operations
- Work on file processing exercises

## ⚠️ Where this breaks

Everything in this notebook is correct, and none of it survives contact with a
real dataset unchanged.

- **Hand-rolled file parsing breaks on real text.** We used `content.split(', ')`.
  One value containing a comma, a quoted field, a Windows line ending or a
  non-UTF-8 byte destroys the result — and destroys it *silently*, handing you a
  wrong list instead of an error. **Use instead:** the `csv` module for delimited
  text, `json` for nested records, pandas (Course 05) for tables.
- **An array is a fixed-type, fixed-size block.** That is where the speed comes
  from and also where the limit is: mixed types, missing values (there is no
  `NaN` in an integer array) and growing row by row all fight the design. Named
  columns of different types are pandas' job, not NumPy's.
- **Our averages assumed clean data.** `sum(data) / len(data)` raises
  `ZeroDivisionError` on an empty list and `TypeError` if one grade is `None`.
  Five tidy numbers hid both failures; the Titanic file you meet in Unit 2 has
  177 missing ages out of 891.
- **Vectorization is not automatically faster.** For a handful of elements, or a
  loop whose body cannot be written as whole-array arithmetic, NumPy's per-call
  overhead makes it *slower* than plain Python. The rule is "vectorize the inner
  loop over data", not "never write a loop".


## 📚 References

1. Harris, C. R., Millman, K. J., van der Walt, S. J., et al. (2020). *Array programming with NumPy*. Nature, 585, 357–362. <https://arxiv.org/abs/2006.10256>
2. McKinney, W. (2010). *Data Structures for Statistical Computing in Python* (pandas). Proceedings of the 9th Python in Science Conference.
3. Pedregosa, F., Varoquaux, G., Gramfort, A., et al. (2011). *Scikit-learn: Machine Learning in Python*. Journal of Machine Learning Research, 12, 2825–2830. <https://arxiv.org/abs/1201.0490>
4. Liang, H., Ma, X., Liu, Z., et al. (2025). *DataFlow: An LLM-Driven Framework for Unified Data Preparation and Workflow Automation in the Era of Data-Centric AI*. arXiv. <https://arxiv.org/abs/2512.16676>
5. Nguyen, C. V., Shen, X., Aponte, R., et al. (2024). *A Survey of Small Language Models*. arXiv. <https://arxiv.org/abs/2410.20011>