# Python for AI Development
## AIAT 111 - Unit 1: Introduction to AI and Applications

---

## 📚 Learning Objectives

By completing this notebook, you will:
- Review Python basics essential for AI development
- Work with lists, dictionaries, loops, and conditionals
- Use NumPy for matrix operations
- Read and write files in Python
- Prepare Python code for AI applications

---

## 🔗 Prerequisites

- ✅ Python 3.8+ installed
- ✅ NumPy installed (`pip install numpy`)
- ✅ Basic Python knowledge

---

## 1. Python Basics Review

Essential Python concepts for AI development:


## 📥 Inputs & 📤 Outputs

**Inputs:** What we use in this notebook

- Libraries and concepts as introduced in this notebook; see prerequisites and code comments.

**Outputs:** What you'll see when you run the cells

- Printed results, figures, and summaries as shown when you run the cells.

---

In [1]:
# Lists - Essential for data manipulation
data_points = [1, 2, 3, 4, 5]
print(f"Data points: {data_points}")
print(f"Sum: {sum(data_points)}")
print(f"Average: {sum(data_points) / len(data_points)}")


Data points: [1, 2, 3, 4, 5]
Sum: 15
Average: 3.0


In [2]:
# Dictionaries - For structured data
student_data = {
    'name': 'Ahmed',
    'age': 22,
    'courses': ['AI', 'ML', 'NLP'],
    'grades': {'AI': 95, 'ML': 88, 'NLP': 92}
}

print(f"Student: {student_data['name']}")
print(f"Average grade: {sum(student_data['grades'].values()) / len(student_data['grades'])}")


Student: Ahmed
Average grade: 91.66666666666667


In [3]:
# Loops - For processing data
scores = [85, 90, 78, 92, 88]
total = 0
for score in scores:
    total += score
    
average = total / len(scores)
print(f"Average score: {average}")

# List comprehension (Pythonic way)
squared = [x**2 for x in range(1, 6)]
print(f"Squared numbers: {squared}")


Average score: 86.6
Squared numbers: [1, 4, 9, 16, 25]


## 2. NumPy for Matrix Operations

NumPy is essential for AI as it provides efficient numerical operations:


In [4]:
import numpy as np

# Creating arrays
vector = np.array([1, 2, 3, 4, 5])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"Vector: {vector}")
print(f"Matrix shape: {matrix.shape}")
print(f"\nMatrix:\n{matrix}")


Vector: [1 2 3 4 5]
Matrix shape: (3, 3)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Matrix operations - Essential for AI

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)
print(f"Matrix A:\n{A}")
print(f"\nMatrix B:\n{B}")
print(f"\nA × B:\n{result}")


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A × B:
[[19 22]
 [43 50]]


In [6]:
# File I/O in Python - Reading and writing files

# Writing to a file
data = "AI, Machine Learning, Deep Learning, NLP"

with open('ai_topics.txt', 'w') as f:
    f.write(data)

print("✅ Data written to file")


✅ Data written to file


In [7]:
# Reading from a file
with open('ai_topics.txt', 'r') as f:
    content = f.read()

print(f"File content: {content}")
topics = content.split(', ')
print(f"\nTopics: {topics}")


File content: AI, Machine Learning, Deep Learning, NLP

Topics: ['AI', 'Machine Learning', 'Deep Learning', 'NLP']


## Summary

In this notebook, we reviewed:
- Python basics: lists, dictionaries, loops, conditionals
- NumPy for matrix operations
- File I/O operations
- Practical data processing for AI

**Next Steps:**
- Complete exercises in `exercises/` folder
- Practice with NumPy operations
- Work on file processing exercises